### ISSUE TITLE
UC2: Create City Weather page

### ISSUE THREAD

**Issue by lizetho** [lizetho/sp-weather-application#2]
**Description**
As a user
Given I am on the home screen
And there is a list of available cities (based on what I've typed)
When I tap on a city
Then I will be on the city Screen
Then I will see the current weather image
Then I will see the current humidity
Then I will see the current weather in text form
Then I will see the current weather temperature

**Comment by lizetho** [comment]
**Subtasks**
- [x] Create UI for City weather page
- [x]  Add Service to retrieve city weather -> https://www.worldweatheronline.com/developer/api/docs/local-city-town-weather-api.aspx
- [x]  Populate View
- [ ] Retrieve Weather image
- [x] Display loader 
- [x]  Handle Errors
- [ ]  Unit tests
